### ISSUE TITLE
questions about the train codes for moco

### ISSUE THREAD

**Issue by mingliutju** [cvl-umass/ContrastLandmark#1]
Hi, thanks for your expressive works, i get two issues in running the train_moco.py, hoping for your help.
1. where is the "equivariance loss"?  i find the infoNEC loss, but missing the the equivariance loss (Equation
3 in the main text) .

2.in the evaluate state, how could the dataset  do augmentations including "RandomResizeCrop", because i did not find the corresponding for the keypoints.

**Comment by ZezhouCheng** [comment]
Hey, thanks for your interest in our work! 
1. In the representation learning stage, we just use image-level contrastive learning loss. The equivariance loss is only used in the feature projection stage. I haven't got the chance to clean up and release the codes of the feature projection but I'm working on it recently. 
2. In the evaluation stage, we did not do any "RandomResizeCrop". The `do_augmentations=False` in this stage (i.e. [here](https://github.com/cvl-umass/ContrastLandmark/blob/master/data_loader/data_loaders_face.py#L306)). In few-shot examples on face benchmarks, we use TPS augmentation (` --TPS_aug`). 
Please let me know if you have any questions.

**Comment by mingliutju** [comment]
Oh, i got it.  i see the description for Training details of feature projection in the paper --"Notice that we do not apply any data augmentations during training", which means that the training paired images have no difference? or  just have geometric and
photometric transformations?

**Comment by ZezhouCheng** [comment]
In the stage of feature projection, we do not apply any augmentations (neither geometric nor photometric deformations). Instead, we simply apply the diversity loss to make the feature descriptors spatially distinct (e.g. left and right eye should have distinct features), and we apply a 1x1 convolutional layer to keep the equivariance of the hypercolumns learned from the image-level contrastive learning.
